# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9b95baf816eed026085cdf131c010e794725d0c3859834ff994ed0b682f4cbb4abb9a4c842f2c53931bf4c9b09b30a36f51224ea7df6db2ecba2faa0e6f3b15

test:
  secret_key_base: 01f5a67834f011373831c976c829e7b670b8231567fe1520922a20de930a7b6a2d6d38cfd7a18bf14ada635f6551eb0bdc71f7b9c148a3e868324440f826b2fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
